"""Unit tests for fitsaudit.core (parser, validators, checksums)."""

import json
import os
import struct
import unittest

from fitsaudit import fixtures
from fitsaudit.core import (
    ACCEPTED,
    REJECTED,
    Reason,
    audit_bytes,
    char_decode,
    char_encode,
    sum32_be,
)
from fitsaudit.fixtures import END_CARD, card, data_block, header_block

DATA_DIR = os.path.join(os.path.dirname(__file__), "data")


def load_fixture(name):
    with open(os.path.join(DATA_DIR, name), "rb") as fh:
        return fh.read()


class ChecksumPrimitiveTests(unittest.TestCase):
    def test_sum32_vectors(self):
        self.assertEqual(sum32_be(b"\x00\x00\x00\x01"), 1)
        self.assertEqual(sum32_be(b"\xff\xff\xff\xff"), 0xFFFFFFFF)
        # 1's complement: all-ones behaves as (negative) zero
        self.assertEqual(sum32_be(b"\xff\xff\xff\xff\x00\x00\x00\x01"), 1)
        self.assertEqual(sum32_be(b"\xff\xff\xff\xff" * 2), 0xFFFFFFFF)
        self.assertEqual(sum32_be(b""), 0)
        # trailing partial word is zero-padded
        self.assertEqual(sum32_be(b"\x00\x00\x00\x01\x01"),
                         sum32_be(b"\x00\x00\x00\x01\x01\x00\x00\x00"))

    def test_char_encode_known_vectors(self):
        # Reference values produced by astropy.io.fits (_char_encode).
        vectors = [
            (0, "0000000000000000"),
            (1, "0000100000000000"),
            (0xFFFFFFFF, "orrrrooooooooooo"),
            (0x2D1ED758, "FA9hF67eFA7eF57e"),
            (0xA5A5A5A5, "YZZZZYYYYYYYYYYY"),
            (123456789, "54Id61Fc51Fc51Fc"),
            (0x0000FFFF, "o00rr00oo00oo00o"),
            (0xFFFF0000, "0rr00oo00oo00oo0"),
        ]
        for value, expected in vectors:
            self.assertEqual(char_encode(value), expected, hex(value))

    def test_char_decode_roundtrip(self):
        for value in (0, 1, 0xFFFFFFFF, 0x2D1ED758, 0xA5A5A5A5,
                      123456789, 0x0000FFFF, 0xFFFF0000, 42, 0x80000000):
            self.assertEqual(char_decode(char_encode(value)), value)
        self.assertIsNone(char_decode("too short"))
        self.assertIsNone(char_decode("\x01" * 16))


class AcceptanceTests(unittest.TestCase):
    def test_minimal_primary_only(self):
        blob = fixtures.primary_hdu()
        report = audit_bytes(blob)
        self.assertEqual(report["conclusion"], ACCEPTED)
        self.assertEqual(report["hduCount"], 1)
        hdu = report["hdus"][0]
        self.assertEqual(hdu["index"], 0)
        self.assertEqual(hdu["type"], "PRIMARY")
        self.assertEqual(hdu["range"], {"start": 0, "end": 2880})
        self.assertEqual(hdu["data"]["bytes"], 0)
        self.assertEqual(hdu["datasum"]["verdict"], "ABSENT")
        self.assertEqual(hdu["checksum"]["verdict"], "ABSENT")
        self.assertIsNone(report["failure"])

    def test_astropy_reference_file(self):
        # Known-answer test against a file generated by astropy
        # (checksum=True), guarding against a self-consistent but
        # non-standard checksum implementation.
        report = audit_bytes(load_fixture("valid_astropy.fits"))
        self.assertEqual(report["conclusion"], ACCEPTED)
        self.assertEqual(report["fileSize"], 8640)
        self.assertEqual(report["hduCount"], 2)
        h0, h1 = report["hdus"]
        self.assertEqual(h0["type"], "PRIMARY")
        self.assertEqual(h0["range"], {"start": 0, "end": 2880})
        self.assertEqual(h0["datasum"],
                         {"verdict": "VALID", "stored": 0, "computed": 0})
        self.assertEqual(h0["checksum"]["verdict"], "VALID")
        self.assertEqual(h0["checksum"]["stored"], "B8dBC7ZBB7dBB7ZB")
        self.assertEqual(h1["type"], "IMAGE")
        self.assertEqual(h1["range"], {"start": 2880, "end": 8640})
        self.assertEqual(h1["data"]["bytes"], 120)
        self.assertEqual(h1["datasum"]["stored"], 202968300)
        self.assertEqual(h1["datasum"]["verdict"], "VALID")
        self.assertEqual(h1["checksum"]["stored"], "LfDeNfCbLfCbLfCb")
        self.assertEqual(h1["checksum"]["verdict"], "VALID")

    def test_built_file_with_extensions(self):
        report = audit_bytes(fixtures.build_valid_file(2))
        self.assertEqual(report["conclusion"], ACCEPTED)
        self.assertEqual(report["hduCount"], 3)
        types = [h["type"] for h in report["hdus"]]
        self.assertEqual(types, ["PRIMARY", "IMAGE", "IMAGE"])
        # ranges are contiguous, half-open and block aligned
        prev_end = 0
        for h in report["hdus"]:
            self.assertEqual(h["range"]["start"], prev_end)
            prev_end = h["range"]["end"]
            self.assertEqual(h["range"]["end"] % 2880, 0)
            self.assertEqual(h["datasum"]["verdict"], "VALID")
            self.assertEqual(h["checksum"]["verdict"], "VALID")
        self.assertEqual(report["fileSize"], prev_end)
        # data sizes follow BITPIX/NAXISn: 6x2 and 6x3 int16 arrays
        self.assertEqual(report["hdus"][1]["data"]["bytes"], 24)
        self.assertEqual(report["hdus"][2]["data"]["bytes"], 36)

    def test_max_hdus_accepted(self):
        report = audit_bytes(fixtures.build_max_hdus_file())
        self.assertEqual(report["conclusion"], ACCEPTED)
        self.assertEqual(report["hduCount"], 16)

    def test_primary_with_data_and_checksums(self):
        data = struct.pack(">10h", *range(-5, 5))
        blob = fixtures.primary_hdu(data, bitpix=16, axes=(10,),
                                    checksums=True)
        report = audit_bytes(blob)
        self.assertEqual(report["conclusion"], ACCEPTED)
        hdu = report["hdus"][0]
        self.assertEqual(hdu["data"]["bytes"], 20)
        self.assertEqual(hdu["datasum"]["verdict"], "VALID")
        self.assertEqual(hdu["checksum"]["verdict"], "VALID")

    def test_header_exactly_fills_block(self):
        # 35 cards + END = 36 cards = exactly one 2880-byte block,
        # leaving zero header-padding bytes.
        cards = [card("SIMPLE", True), card("BITPIX", 8), card("NAXIS", 0)]
        cards += [card("COMMENT", None) for _ in range(32)]
        blob = header_block(cards)
        self.assertEqual(len(blob), 2880)
        report = audit_bytes(blob)
        self.assertEqual(report["conclusion"], ACCEPTED)
        self.assertEqual(report["hdus"][0]["header"]["cards"], 36)

    def test_data_size_uses_pcount_gcount(self):
        # GCOUNT=2, PCOUNT=8, 3x4 int16 image -> 2*(8+12)*2 = 80 bytes
        data = bytes(range(80))
        cards = [card("XTENSION", "IMAGE"), card("BITPIX", 16),
                 card("NAXIS", 2), card("NAXIS1", 3), card("NAXIS2", 4),
                 card("PCOUNT", 8), card("GCOUNT", 2)]
        blob = fixtures.primary_hdu() + header_block(cards) + data_block(data)
        report = audit_bytes(blob)
        self.assertEqual(report["conclusion"], ACCEPTED)
        self.assertEqual(report["hdus"][1]["data"]["bytes"], 80)

    def test_large_file_near_limit(self):
        # Largest block-aligned valid file below the 16 MiB limit.
        data_len = 5824 * 2880 - 2880  # data section padded to 5824 blocks
        cards = [card("SIMPLE", True), card("BITPIX", 8), card("NAXIS", 1),
                 card("NAXIS1", data_len)]
        blob = header_block(cards) + data_block(bytes(data_len))
        self.assertLessEqual(len(blob), 16 * 1024 * 1024)
        report = audit_bytes(blob)
        self.assertEqual(report["conclusion"], ACCEPTED)
        self.assertEqual(report["hdus"][0]["data"]["bytes"], data_len)

    def test_determinism(self):
        blob = fixtures.build_valid_file(2)
        first = json.dumps(audit_bytes(blob), sort_keys=True)
        second = json.dumps(audit_bytes(blob), sort_keys=True)
        self.assertEqual(first, second)


class RejectionTests(unittest.TestCase):
    def assert_rejected(self, blob, reason, hdu=None, offset=None):
        report = audit_bytes(blob)
        self.assertEqual(report["conclusion"], REJECTED, report)
        failure = report["failure"]
        self.assertIsNotNone(failure)
        self.assertEqual(failure["reason"], reason, failure)
        if hdu is not None:
            self.assertEqual(failure["hdu"], hdu, failure)
        if offset is not None:
            self.assertEqual(failure["offset"], offset, failure)
        return report

    def test_empty_file(self):
        self.assert_rejected(b"", Reason.EMPTY_FILE, hdu=0, offset=0)

    def test_truncated_header(self):
        # A two-block header cut after the first block: no END card yet.
        cards = [card("SIMPLE", True), card("BITPIX", 8), card("NAXIS", 0)]
        cards += [card("COMMENT", None) for _ in range(35)]
        blob = header_block(cards)[:2880]
        self.assert_rejected(blob, Reason.TRUNCATED_HEADER, hdu=0, offset=0)

    def test_sub_block_remainder_is_trailing_bytes(self):
        # Fewer than 2880 bytes left after the last complete HDU cannot
        # hold another header block: reported as trailing bytes.
        blob = fixtures.primary_hdu()[:1500]
        self.assert_rejected(blob, Reason.TRAILING_BYTES, hdu=0, offset=0)

    def test_non_ascii_card(self):
        cards = [card("SIMPLE", True), card("BITPIX", 8), card("NAXIS", 0)]
        hdr = bytearray(header_block(cards))
        hdr[100] = 0x07  # BEL inside the second card
        report = self.assert_rejected(bytes(hdr), Reason.INVALID_CARD,
                                      hdu=0, offset=100)
        self.assertEqual(report["failure"]["details"]["byte"], "0x07")

    def test_nonspace_header_padding(self):
        cards = [card("SIMPLE", True), card("BITPIX", 8), card("NAXIS", 0)]
        hdr = bytearray(header_block(cards))
        hdr[500] = 0x00  # after the END card, inside padding
        self.assert_rejected(bytes(hdr), Reason.NONSPACE_HEADER_PADDING,
                             hdu=0, offset=500)

    def test_missing_simple(self):
        cards = [card("BITPIX", 8), card("NAXIS", 0)]
        self.assert_rejected(header_block(cards), Reason.MISSING_KEYWORD,
                             hdu=0, offset=0)

    def test_simple_false(self):
        cards = [card("SIMPLE", False), card("BITPIX", 8), card("NAXIS", 0)]
        self.assert_rejected(header_block(cards),
                             Reason.INVALID_KEYWORD_VALUE, hdu=0, offset=0)

    def test_extension_missing_xtension(self):
        # A concatenated second FITS file starts with SIMPLE, not XTENSION.
        blob = fixtures.primary_hdu() + fixtures.primary_hdu()
        report = self.assert_rejected(blob, Reason.MISSING_KEYWORD, hdu=1,
                                      offset=2880)
        self.assertEqual(report["failure"]["details"]["keyword"], "XTENSION")

    def test_unsupported_extension(self):
        cards = [card("XTENSION", "BINTABLE"), card("BITPIX", 8),
                 card("NAXIS", 2), card("NAXIS1", 4), card("NAXIS2", 2),
                 card("PCOUNT", 0), card("GCOUNT", 1)]
        blob = fixtures.primary_hdu() + header_block(cards) + data_block(b"x" * 8)
        report = self.assert_rejected(blob, Reason.UNSUPPORTED_EXTENSION,
                                      hdu=1, offset=2880)
        self.assertEqual(report["failure"]["details"]["extension"], "BINTABLE")

    def test_invalid_bitpix(self):
        cards = [card("SIMPLE", True), card("BITPIX", 12), card("NAXIS", 0)]
        self.assert_rejected(header_block(cards),
                             Reason.INVALID_KEYWORD_VALUE, hdu=0, offset=80)

    def test_naxis_out_of_range(self):
        cards = [card("SIMPLE", True), card("BITPIX", 8),
                 card("NAXIS", 1000)]
        self.assert_rejected(header_block(cards),
                             Reason.INVALID_KEYWORD_VALUE, hdu=0, offset=160)

    def test_missing_axis_keyword(self):
        cards = [card("SIMPLE", True), card("BITPIX", 8), card("NAXIS", 2),
                 card("NAXIS1", 4)]
        report = self.assert_rejected(header_block(cards),
                                      Reason.MISSING_KEYWORD, hdu=0)
        self.assertEqual(report["failure"]["details"]["keyword"], "NAXIS2")
        # offset points at the END card
        self.assertEqual(report["failure"]["offset"], 4 * 80)

    def test_conflicting_axis_keyword(self):
        cards = [card("SIMPLE", True), card("BITPIX", 8), card("NAXIS", 1),
                 card("NAXIS1", 4), card("NAXIS2", 4)]
        self.assert_rejected(header_block(cards), Reason.KEYWORD_CONFLICT,
                             hdu=0, offset=4 * 80)

    def test_xtension_in_primary_conflicts(self):
        cards = [card("SIMPLE", True), card("BITPIX", 8), card("NAXIS", 0),
                 card("XTENSION", "IMAGE")]
        self.assert_rejected(header_block(cards), Reason.KEYWORD_CONFLICT,
                             hdu=0, offset=3 * 80)

    def test_simple_in_extension_conflicts(self):
        cards = [card("XTENSION", "IMAGE"), card("BITPIX", 8),
                 card("NAXIS", 0), card("PCOUNT", 0), card("GCOUNT", 1),
                 card("SIMPLE", True)]
        blob = fixtures.primary_hdu() + header_block(cards)
        self.assert_rejected(blob, Reason.KEYWORD_CONFLICT, hdu=1,
                             offset=2880 + 5 * 80)

    def test_duplicate_keyword(self):
        cards = [card("SIMPLE", True), card("BITPIX", 8), card("BITPIX", 16),
                 card("NAXIS", 0)]
        self.assert_rejected(header_block(cards), Reason.DUPLICATE_KEYWORD,
                             hdu=0, offset=2 * 80)

    def test_extension_requires_pcount_gcount(self):
        cards = [card("XTENSION", "IMAGE"), card("BITPIX", 8),
                 card("NAXIS", 0)]
        blob = fixtures.primary_hdu() + header_block(cards)
        report = self.assert_rejected(blob, Reason.MISSING_KEYWORD, hdu=1)
        self.assertEqual(report["failure"]["details"]["keyword"], "PCOUNT")

    def test_invalid_gcount(self):
        cards = [card("XTENSION", "IMAGE"), card("BITPIX", 8),
                 card("NAXIS", 0), card("PCOUNT", 0), card("GCOUNT", 0)]
        blob = fixtures.primary_hdu() + header_block(cards)
        self.assert_rejected(blob, Reason.INVALID_KEYWORD_VALUE, hdu=1)

    def test_groups_true_unsupported(self):
        cards = [card("SIMPLE", True), card("BITPIX", 8), card("NAXIS", 0),
                 card("GROUPS", True)]
        self.assert_rejected(header_block(cards), Reason.UNSUPPORTED_FEATURE,
                             hdu=0, offset=3 * 80)

    def test_truncated_data(self):
        full = fixtures.build_valid_file(1)
        cut = full[: 2 * 2880 + 10]  # 10 bytes into HDU 1's data section
        report = self.assert_rejected(cut, Reason.TRUNCATED_DATA, hdu=1,
                                      offset=2 * 2880)
        details = report["failure"]["details"]
        self.assertEqual(details["declaredDataBytes"], 24)
        self.assertEqual(details["fileSize"], len(cut))

    def test_nonzero_data_padding(self):
        data = b"\x01\x02\x03"  # 3 bytes -> 2877 bytes of zero padding
        cards = [card("SIMPLE", True), card("BITPIX", 8), card("NAXIS", 1),
                 card("NAXIS1", 3)]
        blob = bytearray(header_block(cards) + data_block(data))
        blob[2880 + 100] = 0x55  # hide a byte in the padding
        self.assert_rejected(bytes(blob), Reason.NONZERO_DATA_PADDING,
                             hdu=0, offset=2880 + 100)

    def test_trailing_bytes(self):
        blob = fixtures.primary_hdu() + b"\x00" * 100
        report = self.assert_rejected(blob, Reason.TRAILING_BYTES, hdu=1,
                                      offset=2880)
        self.assertEqual(report["failure"]["details"]["trailingBytes"], 100)

    def test_too_many_hdus(self):
        blob = fixtures.build_max_hdus_file() + fixtures.image_hdu(
            b"\x01\x02\x03\x04", bitpix=8, axes=(4,))
        report = self.assert_rejected(blob, Reason.TOO_MANY_HDUS, hdu=16)
        self.assertEqual(report["hduCount"], 16)
        # primary (1 block) + 15 one-block-data extensions (2 blocks each)
        self.assertEqual(report["failure"]["offset"], 2880 + 15 * 2 * 2880)

    def test_datasum_mismatch(self):
        blob = fixtures.corrupt_datasum(fixtures.build_valid_file(1),
                                        occurrence=1)
        report = self.assert_rejected(blob, Reason.DATASUM_MISMATCH, hdu=1)
        details = report["failure"]["details"]
        self.assertEqual(details["stored"], details["computed"] + 1)
        # offset locates the DATASUM card itself
        off = report["failure"]["offset"]
        self.assertEqual(blob[off : off + 8], b"DATASUM ")

    def test_checksum_mismatch(self):
        blob = fixtures.corrupt_checksum(fixtures.build_valid_file(1),
                                         occurrence=1)
        report = self.assert_rejected(blob, Reason.CHECKSUM_MISMATCH, hdu=1)
        off = report["failure"]["offset"]
        self.assertEqual(blob[off : off + 8], b"CHECKSUM")
        details = report["failure"]["details"]
        self.assertEqual(len(details["stored"]), 16)
        self.assertNotEqual(details["stored"], details["computed"])

    def test_corrupt_data_byte_fails_datasum(self):
        blob = fixtures.corrupt_data_byte(fixtures.build_valid_file(1))
        self.assert_rejected(blob, Reason.DATASUM_MISMATCH, hdu=1)

    def test_earliest_failure_wins(self):
        # Both extensions are corrupt; the first failure must be reported.
        blob = fixtures.corrupt_datasum(fixtures.build_valid_file(2),
                                        occurrence=1)
        blob = fixtures.corrupt_checksum(blob, occurrence=2)
        report = self.assert_rejected(blob, Reason.DATASUM_MISMATCH, hdu=1)
        self.assertEqual(report["hduCount"], 1)  # only HDU 0 validated

    def test_malformed_datasum_value(self):
        cards = [card("SIMPLE", True), card("BITPIX", 8), card("NAXIS", 0),
                 card("DATASUM", "not-a-number")]
        self.assert_rejected(header_block(cards),
                             Reason.INVALID_KEYWORD_VALUE, hdu=0)

    def test_oversize_file(self):
        blob = fixtures.primary_hdu() + bytes(16 * 1024 * 1024)
        self.assert_rejected(blob, Reason.FILE_TOO_LARGE, hdu=0,
                             offset=16 * 1024 * 1024)


if __name__ == "__main__":
    unittest.main()
